name: Build IOS
run-name: Build IOS
on:
  workflow_dispatch: {}
jobs:
  Build_IOS:
    runs-on: macos-13.5
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64
    - run: sudo xcode-select --switch /Applications/Xcode_14.3.1.app
    - run: flutter pub get
    - run: flutter build ios --release --no-codesign
    - run: bash /Users/runner/work/PicaComic/PicaComic/.github/generate_ipa.sh
    - uses: actions/upload-artifact@v3
      with:
        name: app-ios.ipa
        path: /Users/runner/work/PicaComic/PicaComic/build/ios/iphoneos/app-ios.ipa
